SELECT * FROM ETL_PROD.LOG.ODOOESP_CONDITIONNEMENT;

SELECT * FROM IRRI_PROD.GOLD_EXT.ODOOESP_TARIF_ACHAT where unite_conditionnement = 'PAL28000';
SELECT ITMREF_0, PCU_0,PCU_1,PCU_2,PCU_3 FROM IRRI_PROD.BRONZE.SAGEX3_ZZVITEM_PIM where ITMREF_0 = '434141';



SELECT
A.CODE_ARTICLE,
LOWER(A.TYPE_COMMANDE) AS TYPE_COMMANDE,
A.ORDRE,
A.QUANTITE,
A.UNITE_CONDITIONNEMENT,
A.UNITE_BASE,
A.TARIF_HT_AU_CONDITIONNEMENT,
A.DATE_UPDATE,
C.LIBELLE AS LIBELLE_CONDITIONNEMENT,
C.UOM_ID AS ID_ODOO_CONDITIONNEMENT
FROM IRRI_PROD.GOLD_EXT.ODOOESP_TARIF_ACHAT A
INNER JOIN ETL_PROD.LOG.ODOOESP_TARIF_ACHAT B ON A.CODE_ARTICLE = B.CODE_ARTICLE AND RESULT = 0 AND COALESCE(B.COUNT_ITERATE,0) <80
LEFT JOIN ETL_PROD.LOG.ODOOESP_CONDITIONNEMENT C ON LOWER(A.UNITE_BASE) = LOWER(COALESCE(C.UNITE, C.LIBELLE)) 
AND LOWER(A.UNITE_CONDITIONNEMENT) = LOWER(COALESCE(C.CONDITIONNEMENT, C.LIBELLE))
WHERE C.LIBELLE IS NULL
order by A.code_article;